version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: >
          docker build -t itdoghr-www:$CIRCLE_BRANCH
          .
      - run: ssh root@$SSH_ADDR docker system prune -a -f
      - run: docker save itdoghr-www:${CIRCLE_BRANCH} | ssh -C root@$SSH_ADDR docker load
      - run: ssh root@$SSH_ADDR "docker rm -f itdoghr-www || true"
      - run: ssh root@$SSH_ADDR docker run --restart=always --name itdoghr-www -d -p 127.0.0.1:12000:3000 itdoghr-www:$CIRCLE_BRANCH
workflows:
  version: 2
  build-and-deploy-bot:
    jobs:
      - build:
          filters:
            branches:
              only: prime
